import { CONFIG } from '../core/config.js';

/** Developer-only presentation telemetry; player HUD never depends on this panel. */
export class DebugPanel {
  constructor({renderer,world,remote,performance,player=null,quests=null,dungeon=null,combat=null,save=null}){this.renderer=renderer;this.world=world;this.remote=remote;this.performance=performance;this.player=player;this.quests=quests;this.dungeon=dungeon;this.combat=combat;this.save=save;this.root=document.querySelector('#debug-panel');this.elements=Object.fromEntries(['fps','drawcalls','entities','effects','chunks','zone','target','quest','dungeon','boss-phase','camera','network','save','position'].map((id)=>[id,document.querySelector(`#debug-${id}`)]));document.querySelector('#debug-button').onclick=()=>this.toggle();document.querySelector('#debug-close').onclick=()=>this.toggle(false);if(CONFIG.debug)this.toggle(true);}
  toggle(force){this.root.classList.toggle('hidden',force===undefined?!this.root.classList.contains('hidden'):!force);}
  put(id,value){if(this.elements[id])this.elements[id].textContent=String(value);}
  update(){if(this.root.classList.contains('hidden'))return;const p=this.renderer.player.position,metrics=this.renderer.getPresentationMetrics?.()??{};this.put('fps',this.performance.fps||'--');this.put('drawcalls',metrics.drawCalls??'--');this.put('entities',this.world.spawns.getAlive().length+this.world.npcs.getAll().length+this.world.resources.list().length);this.put('effects',metrics.activeEffects??0);this.put('chunks',`${this.world.streaming.active.size} active / ${metrics.cachedChunks??this.renderer.chunkCache.size} cached`);this.put('zone',this.world.zones.current?.id??'--');this.put('target',this.combat?.targeting?.target?.data?.id??'none');this.put('quest',this.quests?.current?.id??'none');this.put('dungeon',this.dungeon?.state?.('aurel_sanctum')??'--');this.put('boss-phase',this.combat?.targeting?.target?.ai?.phaseIndex!==undefined?this.combat.targeting.target.ai.phaseIndex+1:'--');this.put('camera',metrics.camera?`${metrics.camera.fov.toFixed(0)}° · ${metrics.camera.collision?'near':'clear'}`:'--');this.put('network',this.remote.online?'DEMO ENDPOINT ONLINE':'LOCAL PREDICTION');this.put('save','LOCAL SAVE V2');this.put('position',`${p.x.toFixed(1)}, ${p.z.toFixed(1)}`);}
}
