import { EVENT, GAME_STATE } from '../core/constants.js';
import { ITEMS } from '../data/content.js';
import { PLAYER_ACTIONS } from '../data/combat-data.js';
import { DamageSystem } from './damage-system.js';
import { HitDetection } from './hit-detection.js';
import { TargetingSystem } from './targeting-system.js';
import { SkillSystem } from './skill-system.js';
import { StatusEffectSystem } from './status-effect-system.js';
import { CombatFeedback } from './combat-feedback.js';

export class CombatService {
  constructor({events,player,world,renderer,inventory,quests,loot,gameState}) {this.events=events;this.player=player;this.world=world;this.renderer=renderer;this.inventory=inventory;this.quests=quests;this.loot=loot;this.gameState=gameState;this.damage=new DamageSystem();this.hitDetection=new HitDetection(renderer);this.targeting=new TargetingSystem(events,world.spawns);this.skills=new SkillSystem();this.statusEffects=new StatusEffectSystem();this.feedback=new CombatFeedback(renderer);this.controller=null;this.activeAction=null;this.comboStep=0;this.comboExpires=0;this.guard={active:false,startedAt:0};this.ultimate=100;this.hitStop=0;this.arenaMechanics=new Map();}
  setController(controller){this.controller=controller;}
  update(delta,now){if(!this.gameState.is(GAME_STATE.PLAYING))return;this.hitStop=Math.max(0,this.hitStop-delta);this.updateAction(delta,now);this.statusEffects.update(delta,(targetId,effect)=>this.resolveStatusTick(targetId,effect));const target=this.targeting.update(this.renderer.player.position,this.renderer.getForwardDirection());this.renderer.setLockedTarget(target,this.targeting.locked);const simulationDelta=this.hitStop>0?0:delta;this.world.update(simulationDelta,this.renderer.player.position,{onAttack:(enemy,pattern)=>this.enemyAttack(enemy,pattern),onTelegraph:(enemy,pattern)=>this.enemyTelegraph(enemy,pattern),onBossPhase:(enemy,phase,index)=>this.bossPhase(enemy,phase,index),onEnrage:(enemy)=>this.enrage(enemy)});this.updateArenaMechanics(simulationDelta);this.events.emit('combat:cooldowns',{now,skills:this.skills});this.events.emit('combat:ultimate',{value:this.ultimate,max:100});}
  isGuarding(){return this.guard.active;}
  beginGuard(){if(this.activeAction||this.player.stats.energy<3)return false;this.guard={active:true,startedAt:performance.now()/1000};this.renderer.setPlayerGuard(true);this.events.emit(EVENT.COMBAT_STATE,{state:'guard'});return true;}
  endGuard(){if(!this.guard.active)return;this.guard.active=false;this.renderer.setPlayerGuard(false);this.events.emit(EVENT.COMBAT_STATE,{state:'idle'});}
  toggleTargetLock(){return this.targeting.toggleLock(this.renderer.player.position,this.renderer.getForwardDirection());}
  cycleTarget(){return this.targeting.cycle(this.renderer.player.position,this.renderer.getForwardDirection());}
  useAction(requestedId){if(!this.gameState.is(GAME_STATE.PLAYING))return false;this.feedback.unlock();if(requestedId==='light')return this.startLightCombo();if(requestedId==='dodge'||requestedId==='dash'||requestedId==='potion')return this.useUtility(requestedId);if(this.activeAction||this.guard.active)return false;return this.startAction(requestedId);}
  startLightCombo(){const now=performance.now()/1000;if(this.activeAction){if(this.activeAction.action.id.startsWith('light_')&&this.activeAction.elapsed>this.activeAction.action.windup)this.activeAction.queueLight=true;return false;}const next=now<=this.comboExpires?Math.min(3,this.comboStep+1):1;return this.startAction(`light_${next}`,{comboStep:next});}
  startAction(id,meta={}){const now=performance.now()/1000;const check=this.skills.canUse(id,this.player.stats,now,{ultimate:this.ultimate});if(!check.ok){this.events.emit(EVENT.NOTIFY,{message:check.reason,type:'warning'});return false;}const action=check.action;const facingTarget=this.targeting.target;if(facingTarget&&this.targeting.locked){const direction=facingTarget.position.clone().sub(this.renderer.player.position);this.player.rotation=Math.atan2(direction.x,direction.z);this.renderer.setPlayerFacing(this.player.rotation);}if(id==='ultimate'&&!this.targeting.target){this.events.emit(EVENT.NOTIFY,{message:'궁극기를 집중할 대상이 필요합니다.',type:'warning'});return false;}this.skills.commit(id,this.player.stats,now);if(action.ultimateCost)this.ultimate=Math.max(0,this.ultimate-action.ultimateCost);this.activeAction={action,elapsed:0,resolved:false,queueLight:false,comboStep:meta.comboStep??0};this.controller?.setActionLock(action.windup+action.active+action.recovery);this.player.state='attack';this.renderer.playPlayerAction(action,this.targeting.target?.position);this.feedback.playerSwing(action);this.events.emit(EVENT.COMBAT_STATE,{state:'attack',action});return true;}
  useUtility(id){const now=performance.now()/1000;const check=this.skills.canUse(id,this.player.stats,now,{ultimate:this.ultimate});if(!check.ok){this.events.emit(EVENT.NOTIFY,{message:check.reason,type:'warning'});return false;}if(id==='potion'&&this.inventory.quantity('dew_vial')<1){this.events.emit(EVENT.NOTIFY,{message:'이슬 약병이 없습니다',type:'warning'});return false;}const action=this.skills.commit(id,this.player.stats,now);if(id==='dodge'){this.controller?.beginDodge();this.renderer.playDodgeEffect();}else if(id==='dash'){this.controller?.beginDash();this.renderer.playDashEffect();}else if(id==='potion'){this.inventory.remove('dew_vial',1);const healing=this.player.stats.heal(ITEMS.dew_vial.heal);this.renderer.createFloatingEffect(this.renderer.player.position,'heal');this.events.emit(EVENT.DAMAGE,{source:'player',target:'player',amount:healing,kind:'heal'});}this.events.emit(EVENT.COMBAT_STATE,{state:id,action});return true;}
  updateAction(delta,now){const active=this.activeAction;if(!active)return;active.elapsed+=delta;const action=active.action;if(!active.resolved&&active.elapsed>=action.windup){active.resolved=true;this.resolvePlayerAction(action);}
    if(active.elapsed>=action.windup+action.active+action.recovery){this.activeAction=null;if(action.id.startsWith('light_')){this.comboStep=active.comboStep;this.comboExpires=now+action.comboWindow;if(active.queueLight)this.startLightCombo();}else {this.comboStep=0;this.comboExpires=0;}this.events.emit(EVENT.COMBAT_STATE,{state:'idle'});}}
  resolvePlayerAction(action){const targets=this.hitDetection.getTargets(this.renderer.player.position,this.player.rotation,this.world.spawns.getAlive(),action);if(!targets.length){this.renderer.playMissEffect(this.renderer.player.position,action);return;}this.events.emit('network:intent',{type:'combat',action:action.id,targetId:targets[0].id});for(const target of targets){const weak=this.world.spawns.ai.isWeakPointOpen(target);const result=this.damage.resolvePlayerHit(action,this.player.stats,target,{bonusMultiplier:weak?1.7:1});this.applyDamage(target,result,{action,weak});}}
  applyDamage(target,result,{action,weak=false,statusTick=false}={}){target.health=Math.max(0,target.health-result.amount);target.hitTimer=.16;const staggered=this.world.spawns.ai.addStagger(target,action?.stagger??0);if(action?.status)this.statusEffects.apply(target.id,action.status);this.renderer.hitEnemy(target,result.type,{heavy:(action?.stagger??0)>=35,weak,staggered});this.renderer.addCameraShake(action?.shake??.08,.11);this.hitStop=Math.max(this.hitStop,action?.hitStop??.03);this.feedback.impact({critical:result.critical,type:result.type,heavy:(action?.stagger??0)>=35});this.events.emit(EVENT.DAMAGE,{source:'player',target,amount:result.amount,critical:result.critical,kind:result.type,weak,staggered,statusTick});this.ultimate=Math.min(100,this.ultimate+Math.max(3,Math.round(result.amount*.16)));if(staggered)this.events.emit(EVENT.NOTIFY,{message:`${target.data.name}의 자세가 무너졌습니다!`,type:'success'});if(target.health<=0)this.kill(target);}
  resolveStatusTick(targetId,effect){if(targetId===this.player.id){if(effect.damage>0){const amount=this.player.stats.takeDamage(effect.damage);this.events.emit(EVENT.DAMAGE,{source:'status',target:'player',amount,kind:effect.id});if(this.player.stats.health<=0)this.events.emit('player:death',{});}return;}const target=this.world.spawns.getAlive().find((entry)=>entry.id===targetId);if(!target)return;if(effect.stun)this.world.spawns.ai.stun(target,effect.stun);if(effect.damage>0){this.applyDamage(target,{amount:effect.damage,critical:false,type:effect.id==='bleed'?'bleed':'poison'},{statusTick:true});}}
  enemyTelegraph(enemy,pattern){this.feedback.enemyTelegraph(enemy.data.boss);this.events.emit('combat:enemy-telegraph',{enemy,pattern});}
  enemyAttack(enemy,pattern){if(!this.gameState.is(GAME_STATE.PLAYING)||!enemy.alive)return;const distance=enemy.position.distanceTo(this.renderer.player.position);if(distance>pattern.range+(pattern.projectile?1.5:0))return;if(this.controller?.isInvulnerable()){this.renderer.playEvadeEffect(this.renderer.player.position);this.events.emit(EVENT.NOTIFY,{message:'완벽 회피',type:'success'});this.ultimate=Math.min(100,this.ultimate+8);return;}
    const now=performance.now()/1000;if(this.guard.active){const parry=now-this.guard.startedAt<=.2;if(parry){this.world.spawns.ai.stun(enemy,enemy.data.boss?1.5:1.1);this.endGuard();this.renderer.playParryEffect(this.renderer.player.position);this.renderer.addCameraShake(.18,.1);this.feedback.guard(true);this.ultimate=Math.min(100,this.ultimate+16);this.events.emit(EVENT.NOTIFY,{message:'완벽 방어 · 적이 경직되었습니다',type:'success'});return;}if(this.player.stats.spendEnergy(6)){const result=this.damage.resolveEnemyHit(pattern,enemy,this.player.stats,{guardMultiplier:.28});this.receiveEnemyDamage(enemy,pattern,result,true);return;}this.endGuard();this.events.emit(EVENT.NOTIFY,{message:'방어가 무너졌습니다',type:'warning'});}
    const result=this.damage.resolveEnemyHit(pattern,enemy,this.player.stats);this.receiveEnemyDamage(enemy,pattern,result,false);}
  receiveEnemyDamage(enemy,pattern,result,guarded){const actual=this.player.stats.takeDamage(result.amount);if(pattern.status)this.statusEffects.apply(this.player.id,pattern.status);const push=this.renderer.player.position.clone().sub(enemy.position);this.controller?.applyKnockback(push,guarded?2:pattern.knockback??3.5);this.renderer.playEnemyAttack(enemy,pattern);this.renderer.addCameraShake(guarded ? .1 : .26,.13);this.feedback.guard(guarded);this.events.emit(EVENT.DAMAGE,{source:enemy,target:'player',amount:actual,kind:result.type,guarded});if(this.player.stats.health<=0)this.events.emit('player:death',{});}
  updateArenaMechanics(delta){for(const [id,mechanic] of this.arenaMechanics){if(!mechanic.boss.alive||!mechanic.boss.active){this.arenaMechanics.delete(id);continue;}mechanic.timer-=delta;if(mechanic.timer>0)continue;mechanic.timer=mechanic.phase.arena==='pulse'?2.45:3.2;const distance=mechanic.boss.position.distanceTo(this.renderer.player.position);const innerSafe=mechanic.phase.arena==='brambles'&&distance<3.2;this.renderer.playArenaHazard(mechanic.boss,mechanic.phase);if(!innerSafe)this.enemyAttack(mechanic.boss,{id:'arena_mechanic',type:mechanic.phase.arena==='pulse'?'light':'poison',damage:mechanic.phase.arena==='pulse'?16:11,range:12,area:true,knockback:2.2});}}
  bossPhase(enemy,phase,index){this.arenaMechanics.set(enemy.id,{boss:enemy,phase,timer:2.1});this.renderer.playBossPhaseEffect(enemy,phase);this.events.emit(EVENT.BOSS_PHASE,{boss:enemy,phase,index});this.events.emit(EVENT.NOTIFY,{message:`${enemy.data.name} · ${phase.label} 단계`,type:'warning'});}
  enrage(enemy){this.renderer.playEnrageEffect(enemy);this.events.emit(EVENT.NOTIFY,{message:`${enemy.data.name}이(가) 격노했습니다!`,type:'error'});}
  kill(enemy){this.world.spawns.remove(enemy);this.targeting.clear(enemy);this.quests.advance('kill',enemy.data.id);const levels=this.player.stats.gainXp(enemy.data.xp);const loot=this.loot.grant(enemy.data.loot);this.renderer.createLootBurst(enemy.position);this.events.emit(EVENT.NOTIFY,{message:`${enemy.data.name} 처치 · EXP +${enemy.data.xp}`,type:'info'});for(const level of levels)this.events.emit(EVENT.NOTIFY,{message:`레벨 ${level} 달성! 능력치가 성장했습니다.`,type:'success'});for(const drop of loot){const item=ITEMS[drop.itemId];this.events.emit(EVENT.NOTIFY,{message:`${item.name} ×${drop.quantity} 획득`,type:'success'});} }
}
