import * as THREE from 'three';
import { EVENT, GAME_STATE } from '../core/constants.js';
import { ITEMS } from '../data/content.js';
import { DamageSystem } from './damage-system.js';
import { TargetingSystem } from './targeting-system.js';
import { SkillSystem } from './skill-system.js';
import { StatusEffectSystem } from './status-effect-system.js';
export class CombatService {
  constructor({events,player,world,renderer,inventory,quests,loot,gameState}) { this.events=events;this.player=player;this.world=world;this.renderer=renderer;this.inventory=inventory;this.quests=quests;this.loot=loot;this.gameState=gameState;this.damage=new DamageSystem();this.targeting=new TargetingSystem(events,world.spawns);this.skills=new SkillSystem();this.statusEffects=new StatusEffectSystem();this.controller=null;this.attackLock=0; }
  setController(controller){this.controller=controller;}
  update(delta,now){if(!this.gameState.is(GAME_STATE.PLAYING))return;this.attackLock=Math.max(0,this.attackLock-delta);this.targeting.update(this.renderer.player.position);this.statusEffects.update(delta);this.world.update(delta,this.renderer.player.position,(enemy)=>this.enemyAttack(enemy));this.events.emit('combat:cooldowns',{now,skills:this.skills});}
  useSkill(id){if(!this.gameState.is(GAME_STATE.PLAYING))return false;const now=performance.now()/1000;const result=this.skills.canUse(id,this.player.stats,now);if(!result.ok){this.events.emit(EVENT.NOTIFY,{message:result.reason,type:'warning'});return false;}const skill=result.skill;if(id==='dodge'){this.skills.commit(id,this.player.stats,now);this.controller?.beginDodge();this.renderer.playDodgeEffect();this.events.emit(EVENT.NOTIFY,{message:'회피',type:'info'});return true;}if(id==='potion'){if(this.inventory.quantity('dew_vial')<1){this.events.emit(EVENT.NOTIFY,{message:'이슬 약병이 없습니다',type:'warning'});return false;}this.skills.commit(id,this.player.stats,now);this.inventory.remove('dew_vial',1);const healing=this.player.stats.heal(ITEMS.dew_vial.heal);this.renderer.createFloatingEffect(this.renderer.player.position,'heal');this.events.emit(EVENT.DAMAGE,{source:'player',target:'player',amount:healing,kind:'heal'});return true;}if(this.attackLock>0)return false;const target=this.targeting.target;const distance=target?.position.distanceTo(this.renderer.player.position)??Infinity;if(!target||distance>skill.range){this.events.emit(EVENT.NOTIFY,{message:'사정거리 안에 적이 없습니다',type:'warning'});return false;}this.skills.commit(id,this.player.stats,now);this.attackLock=skill.cooldown*.55;this.renderer.playPlayerAttack(id,target.position);const calculation=this.damage.calculate({base:skill.damage,attack:this.player.stats.attack,defense:target.data.defense,criticalChance:id==='arcane'?.18:.11});this.applyDamage(target,calculation.amount,{critical:calculation.critical,skill});this.events.emit('network:intent',{type:'combat',skill:id,targetId:target.id});return true;}
  applyDamage(target,amount,{critical=false,skill}={}) { target.health=Math.max(0,target.health-amount);target.hitTimer=.16;this.renderer.hitEnemy(target,skill?.type);this.events.emit(EVENT.DAMAGE,{source:'player',target,amount,critical,kind:skill?.type??'physical'});if(target.health<=0)this.kill(target); }
  kill(enemy){this.world.spawns.remove(enemy);this.targeting.clear(enemy);this.quests.advance('kill',enemy.data.id);const levels=this.player.stats.gainXp(enemy.data.xp);const loot=this.loot.grant(enemy.data.loot);this.renderer.createLootBurst(enemy.position);this.events.emit(EVENT.NOTIFY,{message:`${enemy.data.name} 처치 · EXP +${enemy.data.xp}`,type:'info'});for(const level of levels)this.events.emit(EVENT.NOTIFY,{message:`레벨 ${level} 달성! 능력치가 성장했습니다.`,type:'success'});for(const drop of loot){const item=ITEMS[drop.itemId];this.events.emit(EVENT.NOTIFY,{message:`${item.name} ×${drop.quantity} 획득`,type:'success'});} }
  enemyAttack(enemy){if(!this.gameState.is(GAME_STATE.PLAYING))return;const calculation=this.damage.calculate({base:enemy.data.attack,defense:this.player.stats.defense,criticalChance:.03});const actual=this.player.stats.takeDamage(calculation.amount);this.renderer.playEnemyAttack(enemy);this.events.emit(EVENT.DAMAGE,{source:enemy,target:'player',amount:actual,kind:'enemy'});if(this.player.stats.health<=0)this.events.emit('player:death',{});}
}
