import * as THREE from 'three';
import { EVENT, WORLD } from '../core/constants.js';
import { ZONES, WORLD_BOUNDS } from '../data/content.js';
import { ZoneManager } from './zone-manager.js';
import { EnvironmentManager } from './environment-manager.js';
import { SpawnManager } from './spawn-manager.js';
import { NPCManager } from './npc-manager.js';
import { ChunkStreamingManager } from './chunk-streaming-manager.js';
import { ResourceManager } from './resource-manager.js';
import { WorldNavigation } from './world-navigation.js';

export class WorldManager {
  constructor(events,renderer,quests,inventory,saved={}) { this.events=events;this.renderer=renderer;this.quests=quests;this.zones=new ZoneManager(events);this.environment=new EnvironmentManager(renderer);this.streaming=new ChunkStreamingManager(events,renderer,{radius:1});this.spawns=new SpawnManager(events,renderer);this.npcs=new NPCManager(events,renderer,quests);this.resources=new ResourceManager(events,renderer,inventory);this.navigation=new WorldNavigation(events,saved.navigation);this.resources.restore(saved.resources);this.spawns.restore(saved.spawns);this.interactables=[];this.lastZone=null;this.events.on(EVENT.QUEST_CHANGED,()=>this.navigation.updateMarkers(this.zones.current,this.quests)); }
  async initialize() { this.renderer.createWorld(); }
  activate(position){this.syncStreaming(position,true);this.zones.update(position);this.onZoneChanged(this.zones.current);}
  getGroundHeight(x,z){return this.renderer.getGroundHeight(x,z);}
  constrainPosition(position) { position.x=Math.max(WORLD_BOUNDS.minX+2,Math.min(WORLD_BOUNDS.maxX-2,position.x));position.z=Math.max(WORLD_BOUNDS.minZ+2,Math.min(WORLD_BOUNDS.maxZ-2,position.z)); }
  syncStreaming(position,force=false){const stream=this.streaming.update(position);if(stream.changed||force){const keys=stream.activeKeys;this.spawns.sync(keys);this.npcs.sync(keys);this.resources.sync(keys);this.rebuildInteractables(keys);}}
  rebuildInteractables(activeKeys){const waypointEntities=[];const poiEntities=[];for(const zone of Object.values(ZONES)){for(const waypoint of zone.waypoints){if(activeKeys.has(this.streaming.keyAt(waypoint.position)))waypointEntities.push({id:waypoint.id,type:'waypoint',data:waypoint,position:new THREE.Vector3(waypoint.position.x,this.getGroundHeight(waypoint.position.x,waypoint.position.z),waypoint.position.z)});}for(const poi of zone.pois){if(activeKeys.has(this.streaming.keyAt(poi.position)))poiEntities.push({id:poi.id,type:'poi',data:poi,position:new THREE.Vector3(poi.position.x,this.getGroundHeight(poi.position.x,poi.position.z),poi.position.z)});}}
    const campfire=this.renderer.campfire?{id:'campfire',type:'campfire',data:{name:'길잡이 불씨',text:'따뜻한 불씨가 세계수 광장의 길을 비춥니다.'},position:new THREE.Vector3(-10,0,10),object:this.renderer.campfire}:null;
    this.interactables=[...this.npcs.getAll(),...this.resources.list(),...waypointEntities,...poiEntities,...(campfire?[campfire]:[])]; }
  onZoneChanged(zone){if(!zone||this.lastZone?.id===zone.id)return;this.lastZone=zone;this.environment.setZone(zone);const discovered=this.navigation.discoverZone(zone);for(const waypoint of zone.waypoints)if(waypoint.discovered)this.navigation.discoverWaypoint(waypoint);this.navigation.updateMarkers(zone,this.quests);if(discovered)this.events.emit('ui:notify',{message:`새 지역 발견: ${zone.name}`,type:'success'});}
  update(delta,playerPosition,attackPlayer) { const zone=this.zones.update(playerPosition);this.syncStreaming(playerPosition);this.onZoneChanged(zone);this.environment.update(delta,zone);this.npcs.update(playerPosition);this.spawns.update(delta,playerPosition,attackPlayer); }
  getNearestInteractable(position,range=WORLD.INTERACTION_RANGE) { let found=null;let best=range;for(const entity of this.interactables){const distance=entity.position.distanceTo(position);if(distance<best){best=distance;found=entity;}}return found; }
  interact(entity) { if(entity.type==='npc')return this.npcs.interact(entity);if(entity.type==='resource')return this.resources.interact(entity);if(entity.type==='waypoint'){const discovered=this.navigation.discoverWaypoint(entity.data);this.events.emit('ui:dialogue',{speaker:entity.data.name,text:discovered?'표석이 세계수의 길과 공명합니다. 이제 월드 맵에서 이곳으로 이동할 수 있습니다.':'이미 기록한 표석입니다. 월드 맵에서 이동할 수 있습니다.'});return true;}if(entity.type==='poi'){this.events.emit('ui:dialogue',{speaker:entity.data.name,text:entity.data.type==='dungeon'?'입구 너머는 아직 인스턴스 던전 시스템이 필요한 미지의 영역입니다.':'주변에서 새로운 흔적을 발견했습니다.'});return true;}if(entity.type==='campfire'){this.events.emit('ui:dialogue',{speaker:entity.data.name,text:entity.data.text});return true;}return false; }
  fastTravel(waypointId,player){let destination=null;for(const zone of Object.values(ZONES)){const waypoint=zone.waypoints.find((entry)=>entry.id===waypointId);if(waypoint)destination={zone,waypoint};}if(!destination||!this.navigation.discoveredWaypoints.has(waypointId)){this.events.emit('ui:notify',{message:'아직 연결되지 않은 표석입니다.',type:'warning'});return false;}player.position.x=destination.waypoint.position.x;player.position.z=destination.waypoint.position.z;this.renderer.player.position.set(player.position.x,this.getGroundHeight(player.position.x,player.position.z),player.position.z);this.syncStreaming(this.renderer.player.position,true);this.zones.update(this.renderer.player.position);this.onZoneChanged(destination.zone);this.events.emit('ui:notify',{message:`${destination.waypoint.name}(으)로 이동했습니다.`,type:'success'});return true; }
  snapshot(){return {navigation:this.navigation.snapshot(),resources:this.resources.snapshot(),spawns:this.spawns.snapshot()};}
}
