import { EVENT } from '../core/constants.js';
import { ITEM_DATABASE } from '../data/rpg-content.js';
/** Trusted-event reward subscriber. A network authority can replace resolve() in multiplayer. */
export class RewardService {
  constructor({events,player,inventory,loot,resolve=null}){this.events=events;this.player=player;this.inventory=inventory;this.loot=loot;this.resolve=resolve;events.on(EVENT.ENEMY_DEFEATED,(payload)=>this.onEnemyDefeated(payload));events.on(EVENT.QUEST_TURN_IN,({quest})=>this.grantQuest(quest));events.on('dungeon:completed',({dungeon})=>this.grant(dungeon.completionReward,{kind:'dungeon',sourceId:dungeon.id}));events.on('world:resource-collected',({resource,item,position})=>this.grant({items:[{itemId:item.id,quantity:1}]},{kind:'resource',sourceId:resource.id,position}));}
  onEnemyDefeated({enemy}){if(!enemy?.data?.id)return;const base={xp:Math.max(1,Math.round(enemy.data.xp??0)),gold:Math.max(2,Math.round(enemy.data.gold??(enemy.data.xp??10)*.45)),items:this.loot.plan(enemy.data.id,{rolls:enemy.data.elite?2:1,context:{boss:Boolean(enemy.data.boss)}})};this.grant(this.resolve?this.resolve({kind:'enemy',enemyId:enemy.data.id,base}):base,{kind:'enemy',sourceId:enemy.data.id,position:enemy.position});}
  grantQuest(quest){if(!quest?.id)return false;return this.grant(quest.rewards,{kind:'quest',sourceId:quest.id});}
  grant(reward,{kind='unknown',sourceId='unknown',position=null}={}){if(!this.validReward(reward))return false;const items=[];for(const entry of reward.items??[]){if(!this.inventory.add(entry.itemId,entry.quantity,{silent:true})){this.events.emit(EVENT.NOTIFY,{message:'가방이 가득 차 보상 일부를 받을 수 없습니다.',type:'warning'});break;}items.push({...entry});}const levels=this.player.stats.gainXp(reward.xp??0);this.player.addGold(reward.gold??0);for(const unlock of reward.unlocks??[])this.player.unlock(unlock);const payload={kind,sourceId,xp:reward.xp??0,gold:reward.gold??0,items,levels,unlocks:reward.unlocks??[]};this.events.emit(EVENT.PLAYER_PROGRESS,payload);this.events.emit(EVENT.REWARD_GRANTED,payload);if(position)this.events.emit('reward:world-drop',{position,items});return true;}
  validReward(reward){if(!reward||typeof reward!=='object')return false;if(!Number.isFinite(reward.xp??0)||(reward.xp??0)<0||(reward.xp??0)>100000||!Number.isFinite(reward.gold??0)||(reward.gold??0)<0||(reward.gold??0)>100000)return false;return (reward.items??[]).every((entry)=>ITEM_DATABASE[entry.itemId]&&Number.isInteger(entry.quantity)&&entry.quantity>0&&entry.quantity<=99);}
}
