import { EVENT } from '../core/constants.js';
import { ITEMS, SKILLS } from '../data/content.js';
import { DAMAGE_TYPES } from '../data/combat-data.js';
export class HUD {
  constructor({events,player,inventory,quests,renderer}) {this.events=events;this.player=player;this.inventory=inventory;this.quests=quests;this.renderer=renderer;this.target=null;this.targetLocked=false;this.bossPhase=null;this.elements={healthFill:document.querySelector('#health-fill'),healthText:document.querySelector('#health-text'),energyFill:document.querySelector('#energy-fill'),energyText:document.querySelector('#energy-text'),xpFill:document.querySelector('#xp-fill'),xpText:document.querySelector('#xp-text'),level:document.querySelector('#level-badge'),state:document.querySelector('#player-state'),target:document.querySelector('#target-frame'),targetName:document.querySelector('#target-name'),targetLevel:document.querySelector('#target-level'),targetFill:document.querySelector('#target-health-fill'),targetLock:document.querySelector('#target-lock-state'),targetStatuses:document.querySelector('#target-statuses'),boss:document.querySelector('#boss-frame'),bossName:document.querySelector('#boss-name'),bossPhase:document.querySelector('#boss-phase'),bossStatus:document.querySelector('#boss-status'),bossFill:document.querySelector('#boss-health-fill'),interact:document.querySelector('#interaction-prompt'),interactText:document.querySelector('#interaction-text'),objectiveTitle:document.querySelector('#objective-title'),objectiveProgress:document.querySelector('#objective-progress'),zoneName:document.querySelector('#zone-name'),zoneSubtitle:document.querySelector('#zone-subtitle'),potion:document.querySelector('#potion-count'),ultimate:document.querySelector('#ultimate-percent'),flash:document.querySelector('#hit-flash'),damageLayer:document.querySelector('#combat-text-layer')};this.bind();this.render();}
  bind(){this.events.on(EVENT.PLAYER_CHANGED,({player})=>{this.player=player;this.renderPlayer();});this.events.on(EVENT.TARGET_CHANGED,({target,locked})=>{this.target=target;this.targetLocked=Boolean(locked);this.renderTarget();});this.events.on(EVENT.INTERACTION,({entity})=>{this.elements.interact.classList.toggle('hidden',!entity);if(entity)this.elements.interactText.textContent=entity.type==='npc'?`${entity.data.name}와 대화`:entity.type==='resource'?`${entity.data.name} 채집`:`${entity.data.name} 조사`;});this.events.on(EVENT.QUEST_CHANGED,()=>this.renderQuest());this.events.on(EVENT.INVENTORY_CHANGED,()=>this.renderInventory());this.events.on(EVENT.PLAYER_PROGRESS,()=>this.renderPlayer());this.events.on(EVENT.EQUIPMENT_CHANGED,()=>this.renderPlayer());this.events.on(EVENT.DAMAGE,(payload)=>this.displayDamage(payload));this.events.on('combat:cooldowns',({now,skills})=>this.renderCooldowns(now,skills));this.events.on('combat:ultimate',({value,max})=>{this.elements.ultimate.textContent=Math.round(value/max*100);});this.events.on(EVENT.BOSS_PHASE,({boss,phase,index})=>{this.bossPhase={boss,phase,index};if(this.target===boss)this.renderTarget();});this.events.on('world:zone-changed',({zone})=>{this.elements.zoneName.textContent=zone.name;this.elements.zoneSubtitle.textContent=`${zone.subtitle} · ${zone.levelRange}`;});}
  render(){this.renderPlayer();this.renderTarget();this.renderQuest();this.renderInventory();}
  renderPlayer(){const stats=this.player.stats,percent=(value,max)=>`${Math.max(0,Math.min(100,value/max*100))}%`;this.elements.healthFill.style.width=percent(stats.health,stats.maxHealth);this.elements.healthText.textContent=`${Math.ceil(stats.health)} / ${stats.maxHealth}`;this.elements.energyFill.style.width=percent(stats.energy,stats.maxEnergy);this.elements.energyText.textContent=`${Math.ceil(stats.energy)} / ${stats.maxEnergy}`;this.elements.xpFill.style.width=percent(stats.xp,stats.xpToLevel);this.elements.xpText.textContent=`${stats.xp} / ${stats.xpToLevel}`;this.elements.level.textContent=`Lv. ${stats.level}`;this.elements.state.textContent={idle:'탐험 중',run:'이동 중',sprint:'질주 중',dash:'돌진',dodge:'회피',jump:'도약',guard:'방어',staggered:'경직'}[this.player.state]??'전투 중';}
  renderTarget(){const target=this.target;this.elements.target.classList.toggle('hidden',!target);this.elements.boss.classList.toggle('hidden',!target?.data.boss);if(!target)return;this.elements.targetName.textContent=target.data.name;this.elements.targetLevel.textContent=`Lv. ${target.data.level}${target.data.elite?' · 정예':''}`;this.elements.targetFill.style.width=`${Math.max(0,target.health/target.maxHealth*100)}%`;this.elements.targetLock.textContent=this.targetLocked?'◉':'◇';this.elements.targetLock.classList.toggle('locked',this.targetLocked);const statuses=[target.aiState,target.ai?.weakPointOpen?'약점 노출':null].filter(Boolean);this.elements.targetStatuses.innerHTML=statuses.map((status)=>`<span class="status-chip">${status}</span>`).join('');if(target.data.boss){this.elements.bossName.textContent=target.data.name;const phase=this.bossPhase?.boss===target?this.bossPhase.phase:null;const phaseIndex=this.bossPhase?.boss===target?this.bossPhase.index:(target.ai?.phaseIndex??0)+1;this.elements.bossPhase.textContent=`PHASE ${phaseIndex} · ${phase?.label??'각성'}`;this.elements.bossStatus.textContent=target.ai?.enraged?'격노':target.ai?.weakPointOpen?'심장 약점 노출':target.aiState??'전투 준비';this.elements.bossFill.style.width=`${Math.max(0,target.health/target.maxHealth*100)}%`;}}
  renderQuest(){const quest=this.quests.current;if(!quest){this.elements.objectiveTitle.textContent='새로운 경계를 기다리며';this.elements.objectiveProgress.textContent='현재 이용 가능한 의뢰를 완료했습니다';return;}const first=quest.objectives[0];this.elements.objectiveTitle.textContent=quest.title;this.elements.objectiveProgress.textContent=`${first.label} ${this.quests.objectiveProgress(quest,first)} / ${first.required}`;}
  renderInventory(){this.elements.potion.textContent=this.inventory.quantity('dew_vial');}
  renderCooldowns(now,skills){for(const button of document.querySelectorAll('.skill-slot')){const requested=button.dataset.skill;const id=requested==='light'?'light_1':requested;const skill=SKILLS[id];if(!skill)continue;const remaining=skills.remaining(id,now);button.classList.toggle('cooling',remaining>0);button.style.setProperty('--cooldown',String(skill.cooldown?remaining/skill.cooldown:0));}}
  displayDamage({source,target,amount,critical,kind,weak=false,guarded=false}){if(!amount)return;const position=target==='player'?this.renderer.player.position.clone():target.position.clone();position.y+=target==='player'?2:1.5;const screen=this.renderer.worldToScreen(position);if(!screen.visible)return;const value=document.createElement('span');value.className=`damage-number ${target==='player'?'enemy':''} ${kind==='heal'?'heal':''} ${critical?'critical':''}`;value.textContent=`${kind==='heal'?'+':''}${amount}${weak?' ✦':''}${guarded?' ▰':''}`;value.style.color=DAMAGE_TYPES[kind]?.color??'';value.style.left=`${screen.x}px`;value.style.top=`${screen.y}px`;this.elements.damageLayer.append(value);setTimeout(()=>value.remove(),680);if(target==='player'&&kind!=='heal'){this.elements.flash.classList.add('active');setTimeout(()=>this.elements.flash.classList.remove('active'),100);}this.renderPlayer();this.renderTarget();}
}
