import { AUDIO_CUES, MUSIC_STATES } from './audio-manifest.js';
import { EVENT } from '../core/constants.js';

const CHANNELS=['master','music','sfx','combat','ui','ambient','voice'];
/** Audio routing with synthesized fallbacks; asset records can replace cues without changing callers. */
export class AudioService {
  constructor(events,settings){this.events=events;this.settings=settings;this.context=null;this.channels=new Map();this.musicState=null;this.musicGain=null;this.enabled=Boolean(globalThis.AudioContext||globalThis.webkitAudioContext);this.lastCueAt=new Map();this.bind();}
  bind(){this.events.on('audio:unlock',()=>this.unlock());this.events.on('audio:play',({id,options})=>this.play(id,options));this.events.on('audio:music',({state})=>this.setMusicState(state));this.events.on('ui:notify',({type})=>{if(type==='success')this.play('ui.open');else if(type==='warning'||type==='error')this.play('ui.click');});this.events.on(EVENT.PLAYER_CHANGED,({velocity,player})=>{const now=performance.now();if(velocity>.2&&now>(this.nextFootstep??0)){this.nextFootstep=now+(player.state==='sprint'?240:370);this.play('player.footstep',{volume:player.state==='sprint'?1:.55});}});this.events.on(EVENT.BOSS_PHASE,()=>this.play('combat.boss-phase'));this.events.on(EVENT.QUEST_CHANGED,({state})=>{if(state==='completed')this.play('progress.quest');});this.events.on(EVENT.REWARD_GRANTED,({levels,items})=>{if(levels?.length)this.play('progress.level');else if(items?.length)this.play('progress.item');});}
  unlock(){if(!this.enabled)return false;if(!this.context){const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;try{this.context=new Audio();this.createGraph();}catch{return false;}}if(this.context.state==='suspended')this.context.resume?.();return true;}
  createGraph(){const master=this.context.createGain();master.connect(this.context.destination);this.channels.set('master',master);for(const channel of CHANNELS.filter((id)=>id!=='master')){const gain=this.context.createGain();gain.connect(master);this.channels.set(channel,gain);}this.applySettings(this.settings.snapshot());}
  applySettings(values){if(!this.context)return;const map={master:'masterVolume',music:'musicVolume',sfx:'sfxVolume',combat:'combatVolume',ui:'uiVolume',ambient:'ambientVolume',voice:'voiceVolume'};for(const [channel,key] of Object.entries(map)){const gain=this.channels.get(channel);if(gain)gain.gain.setTargetAtTime(values[key],this.context.currentTime,.03);}}
  play(id,{volume=1,pitch=1}={}){const cue=AUDIO_CUES[id];if(!cue||!this.unlock())return false;const now=this.context.currentTime,last=this.lastCueAt.get(id)??-Infinity;if(now-last<.025)return false;this.lastCueAt.set(id,now);const synth=cue.synth;if(!synth)return false;const oscillator=this.context.createOscillator(),gain=this.context.createGain();oscillator.type=synth.type;oscillator.frequency.setValueAtTime(synth.frequency*pitch,now);gain.gain.setValueAtTime(Math.max(.0001,synth.volume*volume),now);gain.gain.exponentialRampToValueAtTime(.0001,now+synth.duration);oscillator.connect(gain).connect(this.channels.get(cue.channel)??this.channels.get('sfx'));oscillator.start(now);oscillator.stop(now+synth.duration);return true;}
  setMusicState(state){if(!Object.values(MUSIC_STATES).includes(state)||state===this.musicState)return;this.musicState=state;/* No music asset ships yet: retain state/crossfade seam and stay silent. */}
  snapshot(){return {enabled:this.enabled,unlocked:Boolean(this.context),musicState:this.musicState,channels:CHANNELS};}
}
